name: Update gist with WakaTime stats

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 * * * *"
    

jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{ 33969f3f7686a55660aed171c790e34b }}
          GIST_ID: 33969f3f7686a55660aed171c790e34b
          WAKATIME_API_KEY: ${{ 09dd3e63-87e1-4ec0-8f06-83556f361b5d }}

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Update-gist
      run:  go run ./cmd/main.go


   
 
